version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    ports:
      - "3001:3001"
    env_file:
      - .env
    depends_on:
      - redis
    networks:
      - shopsense-net

  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    ports:
      - "5173:80"
    networks:
      - shopsense-net

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - shopsense-net

networks:
  shopsense-net:

volumes:
  redis_data:
