import { UnifiedProduct } from './types';

export const MOCK_PRODUCTS: UnifiedProduct[] = [
  {
    id: 'laptop-001',
    source: 'amazon',
    title: 'ASUS ROG Strix G15 Gaming Laptop, AMD Ryzen 7 6800H, 16GB DDR5, 512GB SSD, RTX 4050, 15.6" FHD 144Hz',
    price_inr: 89990,
    rating: 4.4,
    review_count: 2847,
    category: 'laptop',
    affiliate_url: 'https://amazon.in/dp/B0EXAMPLE1?tag=shopsense-21',
    image_url: 'https://placehold.co/400x400/1a1a2e/e94560?text=ROG+Strix',
    specs: {
      Processor: 'AMD Ryzen 7 6800H',
      RAM: '16GB DDR5 4800MHz',
      Storage: '512GB PCIe NVMe SSD',
      GPU: 'NVIDIA GeForce RTX 4050 6GB',
      Display: '15.6" FHD IPS 144Hz',
      Battery: '90Wh, up to 8 hours',
      OS: 'Windows 11 Home',
      Weight: '2.3 kg',
    },
    raw_text: 'ASUS ROG Strix G15 with AMD Ryzen 7 6800H, RTX 4050 6GB, 16GB DDR5, 512GB SSD, 144Hz display. Great for gaming and video editing.',
    reviews: [
      'Excellent gaming laptop for the price. RTX 4050 handles most games at high settings. Fan noise is manageable.',
      'Battery life is surprisingly good for a gaming laptop. Build quality is solid with RGB keyboard.',
      'Runs video editing software smoothly. Premiere Pro and DaVinci Resolve work great.',
      'Gets warm under heavy load but thermal management is decent. Good value for money.',
      'Display could be brighter but 144Hz is smooth. Overall a great purchase under 90k.',
    ],
  },
  {
    id: 'laptop-002',
    source: 'flipkart',
    title: 'Lenovo IdeaPad Slim 5 Intel Core i5-1335U, 16GB RAM, 512GB SSD, 15.6" FHD IPS, Backlit KB',
    price_inr: 56990,
    rating: 4.3,
    review_count: 1923,
    category: 'laptop',
    affiliate_url: 'https://flipkart.com/dl/lenovo-ideapad?affid=shopsense',
    image_url: 'https://placehold.co/400x400/16213e/0f3460?text=IdeaPad+5',
    specs: {
      Processor: 'Intel Core i5-1335U (12th Gen)',
      RAM: '16GB DDR4 3200MHz',
      Storage: '512GB PCIe SSD',
      GPU: 'Intel Iris Xe Graphics',
      Display: '15.6" FHD IPS Anti-Glare',
      Battery: '57Wh, up to 11 hours',
      OS: 'Windows 11 Home',
      Weight: '1.7 kg',
    },
    raw_text: 'Lenovo IdeaPad Slim 5 ultrabook for productivity. Lightweight at 1.7kg with 11hr battery. Great for students and professionals.',
    reviews: [
      'Perfect for college work and light editing. Very portable and battery lasts all day.',
      'Keyboard is comfortable for long typing sessions. Screen is good but not the brightest.',
      'Great value under 60k. Handles multitasking well with 16GB RAM.',
      'Build quality feels premium for the price. Fingerprint reader works flawlessly.',
      'Not for gaming but handles everything else perfectly. Fast SSD boot times.',
    ],
  },
  {
    id: 'laptop-003',
    source: 'amazon',
    title: 'Apple MacBook Air M2 Chip, 8GB RAM, 256GB SSD, 13.6" Liquid Retina, MagSafe',
    price_inr: 99900,
    rating: 4.7,
    review_count: 5621,
    category: 'laptop',
    affiliate_url: 'https://amazon.in/dp/B0EXAMPLE3?tag=shopsense-21',
    image_url: 'https://placehold.co/400x400/2c3e50/ecf0f1?text=MacBook+Air',
    specs: {
      Processor: 'Apple M2 (8-core CPU, 8-core GPU)',
      RAM: '8GB Unified Memory',
      Storage: '256GB SSD',
      GPU: 'Apple M2 8-core GPU',
      Display: '13.6" Liquid Retina, 500 nits',
      Battery: '52.6Wh, up to 18 hours',
      OS: 'macOS Ventura',
      Weight: '1.24 kg',
    },
    raw_text: 'Apple MacBook Air M2. Fanless silent design, 18hr battery, Liquid Retina display. Best for creative professionals.',
    reviews: [
      'Absolutely love the M2 chip performance. Silent operation is a game changer.',
      'Best laptop I have ever owned. Battery easily lasts 14-15 hours real usage.',
      'Display is gorgeous. Build quality is unmatched. Worth every rupee.',
      'Only 8GB RAM can be limiting for heavy multitasking. Consider 16GB variant.',
      'macOS ecosystem is fantastic. AirDrop with iPhone is seamless.',
    ],
  },
  {
    id: 'phone-001',
    source: 'flipkart',
    title: 'Samsung Galaxy S24 Ultra 5G, 12GB RAM, 256GB, 200MP Camera, S-Pen, 6.8" QHD+ AMOLED',
    price_inr: 129999,
    rating: 4.5,
    review_count: 8934,
    category: 'phone',
    affiliate_url: 'https://flipkart.com/dl/samsung-s24ultra?affid=shopsense',
    image_url: 'https://placehold.co/400x400/1a1a2e/e94560?text=S24+Ultra',
    specs: {
      Processor: 'Snapdragon 8 Gen 3',
      RAM: '12GB',
      Storage: '256GB',
      Camera: '200MP + 50MP + 12MP + 10MP',
      Display: '6.8" QHD+ Dynamic AMOLED 2X, 120Hz',
      Battery: '5000mAh, 45W charging',
      OS: 'Android 14, One UI 6.1',
      'Special Features': 'S-Pen, Galaxy AI, IP68',
    },
    raw_text: 'Samsung Galaxy S24 Ultra flagship with 200MP camera, S-Pen, Galaxy AI features, Snapdragon 8 Gen 3.',
    reviews: [
      'Camera is insane. 200MP main sensor captures incredible detail. Night mode is best in class.',
      'Galaxy AI features are genuinely useful. Circle to Search is addictive.',
      'S-Pen integration is smooth. Great for quick notes and document signing.',
      'Battery easily lasts full day. Titanium frame feels premium and durable.',
      'Expensive but you get what you pay for. Best Android phone available.',
    ],
  },
  {
    id: 'phone-002',
    source: 'amazon',
    title: 'OnePlus 12 5G, 12GB RAM, 256GB, Hasselblad Camera, 6.82" 2K LTPO AMOLED, 100W SUPERVOOC',
    price_inr: 64999,
    rating: 4.4,
    review_count: 6721,
    category: 'phone',
    affiliate_url: 'https://amazon.in/dp/B0EXAMPLE5?tag=shopsense-21',
    image_url: 'https://placehold.co/400x400/16213e/e94560?text=OnePlus+12',
    specs: {
      Processor: 'Snapdragon 8 Gen 3',
      RAM: '12GB LPDDR5X',
      Storage: '256GB UFS 4.0',
      Camera: '50MP + 64MP + 48MP Hasselblad',
      Display: '6.82" 2K LTPO AMOLED, 120Hz',
      Battery: '5400mAh, 100W SUPERVOOC',
      OS: 'Android 14, OxygenOS 14',
      'Special Features': 'Hasselblad tuning, IR blaster',
    },
    raw_text: 'OnePlus 12 flagship killer with Hasselblad cameras, 100W charging, Snapdragon 8 Gen 3.',
    reviews: [
      '100W charging is incredible. 0 to 100 in about 25 minutes. Game changer.',
      'Hasselblad color science makes photos look professional. Great camera system.',
      'OxygenOS 14 is clean and fast. No bloatware compared to other brands.',
      'Display is one of the best. 2K AMOLED with 120Hz is buttery smooth.',
      'Great value for a flagship. Competes with phones costing 30k more.',
    ],
  },
  {
    id: 'phone-003',
    source: 'flipkart',
    title: 'Xiaomi 14 5G, 12GB RAM, 256GB, Leica Camera, 6.36" LTPO AMOLED, Snapdragon 8 Gen 3',
    price_inr: 59999,
    rating: 4.3,
    review_count: 3456,
    category: 'phone',
    affiliate_url: 'https://flipkart.com/dl/xiaomi-14?affid=shopsense',
    image_url: 'https://placehold.co/400x400/533483/e94560?text=Xiaomi+14',
    specs: {
      Processor: 'Snapdragon 8 Gen 3',
      RAM: '12GB LPDDR5X',
      Storage: '256GB UFS 4.0',
      Camera: '50MP Leica + 50MP + 50MP',
      Display: '6.36" 1.5K LTPO AMOLED, 120Hz',
      Battery: '4610mAh, 90W HyperCharge',
      OS: 'Android 14, HyperOS',
      'Special Features': 'Leica optics, Dolby Vision',
    },
    raw_text: 'Xiaomi 14 compact flagship with Leica triple cameras, 90W charging, compact 6.36 inch form factor.',
    reviews: [
      'Compact flagship done right. Fits perfectly in hand unlike giant phones.',
      'Leica cameras produce stunning colors. Street photography is excellent.',
      'HyperOS is smooth but has some ads in default apps. Can be disabled.',
      'Battery life is decent for the size. Gets through a full day.',
      'Best compact Android phone in India right now.',
    ],
  },
  {
    id: 'phone-004',
    source: 'amazon',
    title: 'iQOO Neo 9 Pro 5G, 8GB RAM, 128GB, 50MP OIS Camera, 6.78" AMOLED 144Hz, Dimensity 9300',
    price_inr: 29999,
    rating: 4.3,
    review_count: 4521,
    category: 'phone',
    affiliate_url: 'https://amazon.in/dp/B0EXAMPLE7?tag=shopsense-21',
    image_url: 'https://placehold.co/400x400/0f3460/e94560?text=iQOO+Neo9',
    specs: {
      Processor: 'MediaTek Dimensity 9300',
      RAM: '8GB LPDDR5X',
      Storage: '128GB UFS 4.0',
      Camera: '50MP OIS + 8MP Ultrawide',
      Display: '6.78" AMOLED, 144Hz, 1300 nits',
      Battery: '5160mAh, 120W FlashCharge',
      OS: 'Android 14, Funtouch OS 14',
      'Special Features': '120W charging, Gaming mode',
    },
    raw_text: 'iQOO Neo 9 Pro performance beast under 30k with Dimensity 9300, 120W charging, 144Hz AMOLED.',
    reviews: [
      'Best performance under 30k. Dimensity 9300 is a beast in benchmarks and real usage.',
      '120W charging fills the battery in about 20 minutes. Insanely fast.',
      'Display is gorgeous at 144Hz. Great for gaming and scrolling.',
      'Camera is decent for the price but not flagship level. Good in daylight.',
      'Funtouch OS has improved a lot. Much cleaner than before.',
    ],
  },
  {
    id: 'headphones-001',
    source: 'amazon',
    title: 'Sony WH-1000XM5 Wireless ANC Headphones, 30hr Battery, LDAC, Multipoint, Speak-to-Chat',
    price_inr: 26990,
    rating: 4.6,
    review_count: 12456,
    category: 'headphones',
    affiliate_url: 'https://amazon.in/dp/B0EXAMPLE8?tag=shopsense-21',
    image_url: 'https://placehold.co/400x400/2c3e50/e94560?text=Sony+XM5',
    specs: {
      Type: 'Over-ear, Wireless',
      Driver: '30mm',
      ANC: 'Industry-leading Active Noise Cancellation',
      Battery: '30 hours (ANC on)',
      Codec: 'LDAC, AAC, SBC',
      Connectivity: 'Bluetooth 5.2, Multipoint',
      Weight: '250g',
      'Special Features': 'Speak-to-Chat, Adaptive Sound Control',
    },
    raw_text: 'Sony WH-1000XM5 industry-leading ANC headphones with 30hr battery, LDAC hi-res audio, multipoint connection.',
    reviews: [
      'Best noise cancelling headphones money can buy. ANC is phenomenal on flights.',
      'Sound quality with LDAC is incredible. Warm bass, clear mids and highs.',
      'Comfort is amazing for long sessions. Lighter than XM4.',
      'Multipoint connection works well between laptop and phone.',
      'Speak-to-Chat sometimes triggers accidentally but can be disabled.',
    ],
  },
  {
    id: 'headphones-002',
    source: 'flipkart',
    title: 'boAt Rockerz 551ANC Over-Ear Wireless Headphones, Hybrid ANC, 72hr Playtime, Dual EQ Modes',
    price_inr: 2499,
    rating: 4.1,
    review_count: 23456,
    category: 'headphones',
    affiliate_url: 'https://flipkart.com/dl/boat-551anc?affid=shopsense',
    image_url: 'https://placehold.co/400x400/e94560/ffffff?text=boAt+551',
    specs: {
      Type: 'Over-ear, Wireless',
      Driver: '40mm',
      ANC: 'Hybrid Active Noise Cancellation',
      Battery: '72 hours (ANC off), 49 hours (ANC on)',
      Codec: 'AAC, SBC',
      Connectivity: 'Bluetooth 5.3',
      Weight: '220g',
      'Special Features': 'Beast Mode (low latency), ENx Quad Mics',
    },
    raw_text: 'boAt Rockerz 551ANC budget ANC headphones with 72hr battery, hybrid ANC, Beast Mode for gaming.',
    reviews: [
      'Incredible value for under 2500. ANC is not Sony level but decent for the price.',
      'Battery life is insane. Charged once and lasted almost 3 weeks of daily use.',
      'Build quality is okay. Plastic body but feels sturdy enough.',
      'Sound is bass-heavy which is great for Bollywood music and EDM.',
      'Beast Mode is noticeable improvement for mobile gaming. Mic quality is average.',
    ],
  },
  {
    id: 'tablet-001',
    source: 'amazon',
    title: 'Apple iPad Air M1 Chip, 10.9" Liquid Retina, 64GB WiFi, Touch ID, USB-C',
    price_inr: 54900,
    rating: 4.7,
    review_count: 7892,
    category: 'tablet',
    affiliate_url: 'https://amazon.in/dp/B0EXAMPLE10?tag=shopsense-21',
    image_url: 'https://placehold.co/400x400/2c3e50/ecf0f1?text=iPad+Air',
    specs: {
      Processor: 'Apple M1 chip',
      RAM: '8GB',
      Storage: '64GB',
      Display: '10.9" Liquid Retina, P3 color, True Tone',
      Battery: 'Up to 10 hours',
      Camera: '12MP Wide, 12MP Ultra Wide front',
      Connectivity: 'WiFi 6, Bluetooth 5.0, USB-C',
      'Special Features': 'Apple Pencil 2 support, Magic Keyboard support',
    },
    raw_text: 'Apple iPad Air with M1 chip, 10.9 inch Liquid Retina display, USB-C, Apple Pencil 2 support.',
    reviews: [
      'M1 chip makes this iPad incredibly fast. Handles Procreate and LumaFusion easily.',
      'Perfect size for reading, note-taking with Apple Pencil, and media consumption.',
      'Build quality is classic Apple premium. Feels great in hand.',
      '64GB storage fills up fast. Wish base model was 128GB.',
      'Great alternative to iPad Pro if you do not need ProMotion display.',
    ],
  },
  {
    id: 'camera-001',
    source: 'flipkart',
    title: 'Sony Alpha A6400 Mirrorless Camera, 24.2MP APS-C, 4K Video, 180° Flip Screen, E-Mount',
    price_inr: 75990,
    rating: 4.6,
    review_count: 3245,
    category: 'camera',
    affiliate_url: 'https://flipkart.com/dl/sony-a6400?affid=shopsense',
    image_url: 'https://placehold.co/400x400/1a1a2e/00d2ff?text=Sony+A6400',
    specs: {
      Sensor: '24.2MP APS-C Exmor CMOS',
      'Video Resolution': '4K 30fps, 1080p 120fps',
      Autofocus: '425 phase-detect AF points, Real-time Eye AF',
      Display: '3.0" 180° tiltable touchscreen',
      ISO: '100-32000 (expandable to 102400)',
      Mount: 'Sony E-mount',
      Battery: '~410 shots per charge',
      Weight: '403g (body only)',
    },
    raw_text: 'Sony A6400 mirrorless camera for vlogging and photography. Real-time Eye AF, 4K video, flip screen.',
    reviews: [
      'Best vlogging camera in this price range. Flip screen and Eye AF are perfect for content creators.',
      'Autofocus is blazing fast and accurate. Tracks eyes even in low light.',
      '4K video quality is excellent. Great for YouTube content.',
      'Battery life could be better. Carry at least 2 spare batteries.',
      'Compact and lightweight. Great upgrade from smartphone photography.',
    ],
  },
  {
    id: 'laptop-004',
    source: 'flipkart',
    title: 'HP Pavilion 15 AMD Ryzen 5 7530U, 16GB RAM, 512GB SSD, 15.6" FHD IPS, Backlit KB',
    price_inr: 52990,
    rating: 4.2,
    review_count: 3567,
    category: 'laptop',
    affiliate_url: 'https://flipkart.com/dl/hp-pavilion15?affid=shopsense',
    image_url: 'https://placehold.co/400x400/533483/ecf0f1?text=HP+Pavilion',
    specs: {
      Processor: 'AMD Ryzen 5 7530U',
      RAM: '16GB DDR4 3200MHz',
      Storage: '512GB PCIe NVMe SSD',
      GPU: 'AMD Radeon Graphics',
      Display: '15.6" FHD IPS, 250 nits',
      Battery: '41Wh, up to 8 hours',
      OS: 'Windows 11 Home',
      Weight: '1.75 kg',
    },
    raw_text: 'HP Pavilion 15 everyday laptop with Ryzen 5, 16GB RAM, 512GB SSD. Great for students and office work.',
    reviews: [
      'Solid everyday laptop for college. Handles coding, browsing, and Office smoothly.',
      'Lightweight and portable. Good build quality for the price.',
      'Battery lasts about 6-7 hours in real usage. Acceptable.',
      'Screen is decent but not the brightest. Fine for indoor use.',
      'Good value under 55k. Ryzen 5 performs well for multitasking.',
    ],
  },
  {
    id: 'laptop-005',
    source: 'amazon',
    title: 'Acer Nitro V Gaming Laptop, Intel i5-13420H, 16GB DDR5, 512GB SSD, RTX 4060, 15.6" FHD 144Hz',
    price_inr: 74990,
    rating: 4.3,
    review_count: 2134,
    category: 'laptop',
    affiliate_url: 'https://amazon.in/dp/B0EXAMPLE13?tag=shopsense-21',
    image_url: 'https://placehold.co/400x400/0f3460/00d2ff?text=Acer+Nitro',
    specs: {
      Processor: 'Intel Core i5-13420H (13th Gen)',
      RAM: '16GB DDR5 4800MHz',
      Storage: '512GB PCIe Gen 4 SSD',
      GPU: 'NVIDIA GeForce RTX 4060 8GB',
      Display: '15.6" FHD IPS 144Hz',
      Battery: '57Wh, up to 5 hours',
      OS: 'Windows 11 Home',
      Weight: '2.5 kg',
    },
    raw_text: 'Acer Nitro V mid-range gaming laptop with RTX 4060 8GB, 13th gen i5, DDR5 RAM. Best gaming laptop under 75k.',
    reviews: [
      'RTX 4060 is a great GPU for 1080p gaming. Runs most AAA games at high settings.',
      'DDR5 RAM makes a noticeable difference. Overall snappy performance.',
      'Thermals could be better. Use a cooling pad for long gaming sessions.',
      'Build feels a bit plasticky but functional. Good keyboard for gaming.',
      'Best gaming value under 75k. Outperforms competitors at this price.',
    ],
  },
  {
    id: 'phone-005',
    source: 'flipkart',
    title: 'Nothing Phone (2a) Plus 5G, 12GB RAM, 256GB, 50MP Dual Camera, 6.7" AMOLED 120Hz',
    price_inr: 27999,
    rating: 4.4,
    review_count: 5678,
    category: 'phone',
    affiliate_url: 'https://flipkart.com/dl/nothing-phone2a?affid=shopsense',
    image_url: 'https://placehold.co/400x400/1a1a2e/ffffff?text=Nothing+2a',
    specs: {
      Processor: 'MediaTek Dimensity 7350 Pro',
      RAM: '12GB LPDDR5',
      Storage: '256GB UFS 3.1',
      Camera: '50MP + 50MP',
      Display: '6.7" AMOLED, 120Hz, 1100 nits',
      Battery: '5000mAh, 50W charging',
      OS: 'Android 14, Nothing OS 2.5',
      'Special Features': 'Glyph Interface, NFC',
    },
    raw_text: 'Nothing Phone 2a Plus with unique Glyph LED design, clean Nothing OS, 50MP cameras, 120Hz AMOLED.',
    reviews: [
      'Unique design stands out. Glyph interface is actually useful for notifications.',
      'Nothing OS is the cleanest Android skin. Feels like stock with useful additions.',
      'Camera is surprisingly good for the price. Great in daylight, decent at night.',
      'Display is vibrant and smooth. 120Hz AMOLED at this price is great.',
      'Best phone under 30k for people who want something different.',
    ],
  },
  {
    id: 'headphones-003',
    source: 'amazon',
    title: 'Apple AirPods Pro 2nd Gen, USB-C, Active Noise Cancellation, Spatial Audio, MagSafe Case',
    price_inr: 24900,
    rating: 4.7,
    review_count: 18234,
    category: 'headphones',
    affiliate_url: 'https://amazon.in/dp/B0EXAMPLE15?tag=shopsense-21',
    image_url: 'https://placehold.co/400x400/2c3e50/ecf0f1?text=AirPods+Pro',
    specs: {
      Type: 'In-ear, True Wireless',
      Driver: 'Custom Apple driver + amplifier',
      ANC: 'Active Noise Cancellation with Transparency mode',
      Battery: '6hr (buds), 30hr (with case)',
      Codec: 'AAC',
      Connectivity: 'Bluetooth 5.3, H2 chip',
      Weight: '5.3g per earbud',
      'Special Features': 'Spatial Audio, Adaptive EQ, USB-C MagSafe case',
    },
    raw_text: 'Apple AirPods Pro 2 with H2 chip, USB-C, best ANC earbuds for iPhone users, Spatial Audio.',
    reviews: [
      'ANC is incredible for earbuds. Best noise cancelling TWS available.',
      'Spatial Audio with head tracking is amazing for movies and Apple Music.',
      'Seamless integration with Apple ecosystem. Switching between devices is magic.',
      'Comfortable for hours of use. Ear tips seal perfectly.',
      'USB-C finally! No more Lightning. Case speaker for Find My is useful.',
    ],
  },
];
